export const languages = [
  { code: "cs", name: "Cesky", alt: "Cesky", flagCode: "cz" },
  { code: "de", name: "Deutsch", alt: "Deutsch", flagCode: "de" },
  { code: "en", name: "English", alt: "ENGLISH", flagCode: "gb" },
  { code: "es", name: "Español", alt: "Español", flagCode: "es" },
  { code: "el", name: "Ελληνικά", alt: "Ελληνικά", flagCode: "gr" },
  { code: "fr", name: "Français", alt: "FRENCH", flagCode: "fr" },
  { code: "hu", name: "Magyar", alt: "Magyar", flagCode: "hu" },
  { code: "fi", name: "Suomalainen", alt: "Suomalainen", flagCode: "fi" },
  { code: "et", name: "Eesti keel", alt: "Eesti keel", flagCode: "ee" },
  { code: "hi", name: "हिंदी", alt: "Hindi", flagCode: "in" },
  { code: "yue", name: "粵語", alt: "Cantonese", flagCode: "cn" },
  { code: "th", name: "แบบไทย", alt: "Thai", flagCode: "th" },
  { code: "bn", name: "বাংলা", alt: "Bengali", flagCode: "bd" },
  { code: "ms", name: "Melayu", alt: "Malay", flagCode: "my" },
  { code: "ko", name: "한국인", alt: "한국인", flagCode: "kr" },
  { code: "hr", name: "Hrvatski", alt: "Hrvatski", flagCode: "hr" },
  { code: "id", name: "Bahasa Indonesia", alt: "Indonesian", flagCode: "id" },
  { code: "ja", name: "日本語", alt: "Japanese", flagCode: "jp" },
  { code: "sv", name: "Svenska", alt: "Svenska", flagCode: "se" },
  { code: "it", name: "Italiano", alt: "Italiano", flagCode: "it" },
  { code: "bg", name: "Български", alt: "Български", flagCode: "bg" },
  { code: "sr", name: "Српски", alt: "Serbian", flagCode: "rs" },
  { code: "uk", name: "Yкраїнська", alt: "Ukrainian", flagCode: "ua" },
  { code: "he", name: "עִברִית", alt: "Hebrew", flagCode: "il" },
  { code: "sk", name: "Slovenský", alt: "Slovak", flagCode: "sk" },
  { code: "da", name: "Dansk", alt: "Danish", flagCode: "dk" },
  { code: "ar", name: "عربي", alt: "Arabic", flagCode: "sa" },
  { code: "nl", name: "Nederlands", alt: "Nederlands", flagCode: "nl" },
  { code: "no", name: "Norsk", alt: "Norsk", flagCode: "no" },
  { code: "pl", name: "Polski", alt: "Polski", flagCode: "pl" },
  { code: "zh", name: "普通话", alt: "Mandarin", flagCode: "cn" },
  { code: "pt", name: "Português", alt: "Português", flagCode: "pt" },
  { code: "ro", name: "Română", alt: "Romanian", flagCode: "ro" },
  { code: "sl", name: "Slovenščina", alt: "Slovenian", flagCode: "si" },
  { code: "tr", name: "Türk", alt: "turkish", flagCode: "tr" },
  {
    code: "pt-br",
    name: "Português(BR)",
    alt: "Portuguese (BR)",
    flagCode: "br",
  },
  { code: "vi", name: "Tiếng Việt", alt: "Vietnamese", flagCode: "vn" },
  { code: "bs", name: "Bosanski", alt: "Bosnian", flagCode: "ba" },
  { code: "tk", name: "Türkmençe", alt: "Turkmen", flagCode: "tm" },
  { code: "zu", name: "isiZulu", alt: "Zulu", flagCode: "za" },
  { code: "ru", name: "Русский", alt: "Russian", flagCode: "ru" },
  { code: "lv", name: "Latviešu", alt: "Latvian", flagCode: "lv" },
  { code: "lt", name: "Lietuvių", alt: "Lithuanian", flagCode: "lt" },
  { code: "fil", name: "Filipino", alt: "Filipino", flagCode: "ph" },
];